### ISSUE TITLE
Transbank MallTransaction create error

### ISSUE THREAD

**Issue by bawas** [TransbankDevelopers/transbank-sdk-nodejs#14]
**Describe el bug**

Al crear una transacción Mall de la forma en que se indica en la [referencia](https://www.transbankdevelopers.cl/referencia/webpay?l=ruby#webpay-plus-mall)  con el SDK 2.0 de nodejs entrega el error `Error [TransbankError]: Error: Request failed with status code 400
unrecognized field 'details'`
 
**Para reproducir**
```javascript
const buyOrder = 'ordenCompraDetalle1234';
const buyOrder2 = 'ordenCompraDetalle4321';
const amount = 10000;
const amount2 = 12000;
const commerceCode = '597055555536';
const commerceCode2 = '597055555537';
const sessionId = 'mi-session-id';
const returnUrl = 'http://localhost:3000/local/webpay/success';

const details = [
  new Transbank.TransactionDetail(amount, commerceCode, buyOrder),
  new Transbank.TransactionDetail(amount2, commerceCode2, buyOrder2),
];

const result = await Transbank.WebpayPlus.MallTransaction.create(
    buyOrder,
    sessionId,
    returnUrl,
    details,
);
```
Una explicación concisa y clara de qué es lo que esperas que ocurra.

debiese retornar el token y el url del formulario

**Versiones (por favor agrega aquí la siguiente información):**
- SDK: 2.0.0
- Node.js: 12.20.0
- NPM 6.14.8

**Comment by gonzunigad** [comment]
Para ayudar a cualquiera que llegue acá por Google, lo único que faltaba era configurar el SDK para que use el código de comercio de Webpay Plus Mall: `Transbank.WebpayPlus.configureWebpayPlusMallForTesting();` ya que por defecto el SDK viene configurado para funcionar con Webpay Plus (no Mall)
