### ISSUE TITLE
Violación de la licencia

### ISSUE THREAD

**Issue by rgcl** [TransbankDevelopers/transbank-sdk-nodejs#2]
Hola gente de Transbank, advierto que éste repositorio en gran parte es un copy-paste de mi código https://github.com/rgcl/webpay-nodejs, el cuál está licenciado en LGPL, lo que requiere que pongan la advertencia en cada archivo de código fuente y me den crédito.

Igual feo que no me tiren un milloncito al menos, no sé, mínimo para usar mi código con la licencia que quieran. Sé que éste repo está en desarrollo ¿Qué hacemos?

**Comment by gonzunigad** [comment]
Hola Rodrigo. Antes que todo, muchas gracias por el trabajo realizado en tu repositorio. Efectivamente, a nivel de desarrollo hemos usado algunos archivos de este para comenzar, pero debido al licenciamiento de tu proyecto, tenemos que reimplementarlos. 
Como bien dices, este SDK sigue en desarrollo, por lo que ya notarás los cambios en breve. De todas formas, hay un par de clases que igual tendrán una mención en el código (ya están en el nuevo branch)

**Comment by rgcl** [comment]
Mira, o bien (1) rehacen su código desde cero; o bien (2) llegan a un acuerdo comercial conmigo (que sería una ínfima parte de lo que les paga Transbank); o bien (3) distribuyen su librería completa como LGPL, dado que es un una obra [derivada](https://www.gnu.org/licenses/gpl-faq.html#OOPLang).

De cualquier forma junto con acciones legales, están jugando con su reputación como empresa (Continuum), desarrolladores y la propia Transbank.

**Comment by gonzunigad** [comment]
Rodrigo, nuestro objetivo en Transbank Developers es entregar herramientas que tengan soporte a los integradores. Como te comentaba, el código que se lanzará cuando esté listo no usará tus archivos. 
Vamos a cerrar este repositorio mientras esté WIP.
Saludos!
