### ISSUE TITLE
Credenciales del comercio

### ISSUE THREAD

**Issue by wibav** [TransbankDevelopers/transbank-sdk-nodejs#31]
Como asigno las credenciales del comercio en el sdk? para al momento de crear la inscripción salga el nombre del comercio.

**Comment by gonzunigad** [comment]
Hola, está documentado en https://transbankdevelopers.cl/documentacion/como_empezar#b-utilizando-los-sdk

**Comment by wibav** [comment]
Gracias, como critica constructiva seria adecuado cuales se usan en dev y cuales en productivo.
muchas gracias!
