### ISSUE TITLE
Credenciales de banco de prueba

### ISSUE THREAD

**Issue by wibav** [TransbankDevelopers/transbank-sdk-nodejs#32]
Buenas, haciendo pruebas con el SDK la inscripción de tarjeta, no logramos hacer login en el banco de prueba.

Hemos probado con RUT 11.111.111-1 clave 1234 o 123456

pero no logramos pasar de esa pantalla para continuar con el proceso de integración.

Agradezco la ayuda.

![transbank](https://user-images.githubusercontent.com/3717777/115594938-53406f00-a2a4-11eb-8f2e-1a45ecaac01e.png)

**Comment by gonzunigad** [comment]
La clave es 123, como está documentado en https://transbankdevelopers.cl/documentacion/como_empezar#ambiente-de-integracion
