### ISSUE TITLE
Al cancelar transacción con commit TBK_TOKEN

### ISSUE THREAD

**Issue by tonporaqui** [TransbankDevelopers/transbank-sdk-nodejs#37]
**Describe el bug**

Al cancelar la transacción con SDK (según documentación) :

`const response = await WebpayPlus.Transaction.commit(req.body.TBK_TOKEN);`

indica lo siguiente:

```
Error: Request failed with status code 422                                                                                                                                                                                         11:36:36
Invalid status '10' for transaction while authorizing. Commerce will be notified by webpay to authorize


  Invalid status '10' for transaction while authorizing. Commerce will be notified by webpay to authorize

  at new TransbankError (node_modules\transbank-sdk\dist\es5\transbank\common\transbank_error.js:19:28)
```

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/7048226/124951344-413bb600-dfe1-11eb-8067-56ae2a68224c.png)

**Versiones (por favor agrega aquí la siguiente información):**
- SDK: "transbank-sdk": "^2.1.3"
- Node.js: v12.18.4
- NPM: 6.14.6

**Comment by gonzunigad** [comment]
Hola. Al cancelar la transacción no debes hacer "commit"

**Comment by farriagadal** [comment]
Hola @tonporaqui, como lo resolviste? como se cancela una transacción, no me cambia el estado a FAILED
