### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by rodrigo1991** [TransbankDevelopers/transbank-sdk-nodejs#55]
**Cannot read property 'data' of undefined**

al momento de usar la librería y tratar de crear una transacción :
tx.create(buyOrder, sessionId, amount, returnUrl);
aparece el error "Cannot read property 'data' of undefined", al momento de ir a ver el real error en la librería, veo que muere por timeout

**Para reproducir**

llamar al método create de transbank

**Comportamiento observado**

Devuelve un error Cannot read property 'data' of undefined

**Comportamiento esperado**

Debe crear la transacción

**Capturas de pantalla**
incluso aumentándole el timeout de 10000 a 1000000 igual muere por timeout
![image](https://user-images.githubusercontent.com/12146842/150530577-d9011c2d-86c3-4834-bd6c-ab5580225ea8.png)

**Versiones**
- SDK: [3.0.0]
- Node.js: [v16.13.1]
- NPM [8.3.0]

**Comment by eljou** [comment]
Subscribo al comentario de @rodrigo1991  el error se encuentra en este archivo https://github.com/TransbankDevelopers/transbank-sdk-nodejs/blob/master/lib/transbank/common/request_service.ts linea 38 porque se intenta acceder a la propiedad error_message que no existe cuando ocurre un timeout, porfa pueden tratar ese tipo de escenarios y entregar un error mas identificable...

**Comment by driquelmemurua** [comment]
Me ocurre este mismo error cuando intento remover una inscripción de Oneclick Mall, lo raro es que si efectivamente borra la inscripción, tan solo que el error me arruina el resto del flujo

**Comment by olaferlandsen** [comment]
Hola @rodrigo1991 :P
Si no puedes avanzar forkea y usa esto:

```javascript
esponse?.data?.error_message
```
