### ISSUE TITLE
Integración Patpass

### ISSUE THREAD

**Issue by rvillablanca** [TransbankDevelopers/transbank-sdk-nodejs#6]
**Describe el bug**

No se sí es considerado bug, pero puede ser que falte.
 
**Para reproducir**

1. Intentar inicializar una transaccion de patpass

**Comportamiento observado**

El SDK al parecer no ofrece la posibilidad de iniciar un pago con una inscripción patpass

**Comportamiento esperado**

Que sí permita

**Versiones (por favor agrega aquí la siguiente información):**

No es importante en este contexto
**Contexto adicional**

Como dije antes, caé más en la categoría de pregunta más que bug. Este reporte me llegó por otro lado y yo lo levanto por aquí para saber si efectivamente estaría faltando esa feature :)

**Comment by zagalvelozo** [comment]
Efectivamente, este SDK no tiene Integración Patpass, te recomiendo usar el SDK de JAVA.

**Comment by rvillablanca** [comment]
Ok gracias. Con respecto a Java no es una opción en este momento

**Comment by zagalvelozo** [comment]
Entonces la vieja confiable, PHP.

**Comment by zagalvelozo** [comment]
Entonces la vieja confiable, C#.
