### ISSUE TITLE
npm install transbank-sdk instala una version antigua del sdk

### ISSUE THREAD

**Issue by lnavarroa** [TransbankDevelopers/transbank-sdk-nodejs#73]
Hola, estoy trabajando en la integración del sdk node, al realizar las instrucciones que aparecen aquí en github (https://github.com/TransbankDevelopers/transbank-sdk-nodejs), al instalar mediante npm me instala una versión anterior a lo que se tiene publicado aquí en github. 

archivo /node_modules/transbank-sdk/index.js que se me instala

`const Webpay = require('./lib/webpay');
const { Configuration, services, environments } = require('./lib/config');

const Transbank = {};
Transbank.Configuration = Configuration;
Transbank.services = services;
Transbank.environments = environments;
Transbank.Webpay = Webpay;

module.exports = Transbank;`

y en /node_modules/transbank-sdk/lib/ se me instala el archivo webpay.js

**Comment by pmoralesp** [comment]
En npm está publicada la [versión 1.0.4](https://www.npmjs.com/package/transbank-sdk), mientras que acá en github está la versión 4.0.0.

¿Alguien sabe qué pasó? hace algunos meses ambos estaban en la versión 4, pero donwgradearon la versión de npm. ¿Cuál usar?

**Comment by mvarlic** [comment]
Muchas gracias por avisarnos, ya corregimos el problema, la versión 4.0.0 quedo marcada como la 'ultima y es la que se instalará por defecto cuando uses 'npm i transbank-sdk'

**Comment by lnavarroa** [comment]
> Muchas gracias por avisarnos, ya corregimos el problema, la versión 4.0.0 quedo marcada como la 'ultima y es la que se instalará por defecto cuando uses 'npm i transbank-sdk'

gracias
