### ISSUE TITLE
Vulnerabilidad reportada por npm audit

### ISSUE THREAD

**Issue by fagonzalezm** [TransbankDevelopers/transbank-sdk-nodejs#80]
**Describe el bug**

Les escribo para informarles respecto a una vulnerabilidad reportada por npm audit debido a una dependencia con axios ([Axios Cross-Site Request Forgery Vulnerability](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx)).
 
**Para reproducir**

1. Ejecutar npm audit

**Comportamiento observado**

El comando entrega una vulnerabilidad

**Comportamiento esperado**

Que el audit no falle

**Capturas de pantalla**

Desglose del audit:
![image](https://github.com/TransbankDevelopers/transbank-sdk-nodejs/assets/23390523/7c6366f5-3777-4e8f-b9f9-4978a8ddf555)

**Versiones (por favor agrega aquí la siguiente información):**
- SDK: 4.0.0
- Node.js: 20.9.0
- NPM 10.1.0

**Contexto adicional**

Existe un [PR](https://github.com/TransbankDevelopers/transbank-sdk-nodejs/pull/79) generado automáticamente que mitigaría la vulnerabilidad, pero no ha sido tomado.

El correo entregado para reportar la vulnerabilidad no está funcionando, por esto les escribo por este medio.

**Comment by mastudillot** [comment]
Gracias por el reporte.

Esto quedara solucionado en la siguiente versión del SDK
